version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app

  redis:
    image: redis:alpine
    expose: 
      - 5000
    ports: 
      - "5000:5000"

  nginx: 
    image: nginx
    expose: 
      - 8080
    ports:
      - "8080:80"